// GENERATED by scripts/build-email.mjs from emails/lead-confirmation.mjml. Do not edit.
// Tokens ({{PARENT_FIRST_NAME}}, {{CONTACT_METHOD_PHRASE}}, {{SUMMARY_ROWS}}) are
// filled by renderLeadConfirmation() in emails.ts.
export const LEAD_CONFIRMATION_HTML = `<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title>Thank you for reaching out</title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
      <!--[if !mso]><!-->
        <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600&display=swap" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap" rel="stylesheet" type="text/css">
        <style type="text/css">
          @import url(https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600&display=swap);
@import url(https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap);
        </style>
      <!--<![endif]-->

    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
    <style type="text/css">

    @media only screen and (max-width:479px) {
      table.mj-full-width-mobile { width: 100% !important; }
      td.mj-full-width-mobile { width: auto !important; }
    }
  
    </style>
    
    <!-- copy/email.preheader -->
  </head>
  
      <body  style="word-spacing:normal;background-color:#f4ece4;">
        
    <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">I read every message personally and will be back in touch within a day or two.</div>
  
        <div
           aria-label="Thank you for reaching out" aria-roledescription="email" role="article" lang="und" dir="auto" style="word-spacing:normal;background-color:#f4ece4;"
        >
        <!-- Header band -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#b6b791" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#b6b791;background-color:#b6b791;margin:0px auto;max-width:600px;border-radius:14px 14px 0 0;overflow:hidden;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#b6b791;background-color:#b6b791;width:100%;border-collapse:separate;"
        >
          <tbody>
            <tr>
              <td
                 style="border-radius:14px 14px 0 0;direction:ltr;font-size:0px;padding:26px 0 22px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- copy/email.brand -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 32px 6px;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:12px;font-weight:700;letter-spacing:2px;line-height:24px;text-align:center;text-transform:uppercase;color:#fffdf9;"
      >McKenzie Ochoa Conner</div>
    
                </td>
              </tr>
            <!-- copy/email.brand-tag -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 32px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Fraunces, Georgia, 'Times New Roman', serif;font-size:20px;line-height:26px;text-align:center;color:#3f4437;"
      >Nanny care with a teacher's heart</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Photo + greeting -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#fffdf9" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#fffdf9;background-color:#fffdf9;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#fffdf9;background-color:#fffdf9;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:30px 0 0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 32px 22px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"
      >
        <tbody>
          <tr>
            <td  style="width:148px;">
              
      <img
         alt="McKenzie smiling on a sofa, reading a picture book, with baby toys close by" src="https://nannymckenzie.github.io/photos/mckenzie-portrait.jpg" style="border:0;border-radius:14px;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="148" height="auto"
      />
    
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            <!-- copy/email.greeting (deco/email.var.first-name) -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px 12px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Fraunces, Georgia, 'Times New Roman', serif;font-size:24px;line-height:32px;text-align:left;color:#6f5038;"
      >Hi {{PARENT_FIRST_NAME}},</div>
    
                </td>
              </tr>
            <!-- copy/email.thanks (deco/email.var.contact-method) -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px 8px;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:15px;line-height:24px;text-align:left;color:#3f4437;"
      >Thank you so much for reaching out about care for your family. Your note made it to me safely, and I'm really glad you did. I read every message personally, and I'll be back in touch {{CONTACT_METHOD_PHRASE}} within a day or two.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- What happens next -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#fffdf9" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#fffdf9;background-color:#fffdf9;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#fffdf9;background-color:#fffdf9;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:18px 0 0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- copy/email.next-steps.h -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px 10px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Fraunces, Georgia, 'Times New Roman', serif;font-size:18px;font-weight:600;line-height:24px;text-align:left;color:#3f4437;"
      >What happens next</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px 4px;word-break:break-word;"
                >
                  
      <table
         cellpadding="0" cellspacing="0" width="100%" border="0" style="color:#000000;font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;border:none;"
      >
        <!-- copy/email.next-steps.1 -->
          <tr>
            <td width="28" align="left" valign="top" style="padding:0 0 10px;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#896447;font-weight:700;">1.</td>
            <td valign="top" style="padding:0 0 10px;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#3f4437;">I'll reply within a day or two, usually sooner.</td>
          </tr>
          <!-- copy/email.next-steps.2 -->
          <tr>
            <td width="28" align="left" valign="top" style="padding:0 0 10px;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#896447;font-weight:700;">2.</td>
            <td valign="top" style="padding:0 0 10px;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#3f4437;">If it feels like we could be a good match, we'll set up a relaxed introductory call to get to know each other and talk through your family's days.</td>
          </tr>
          <!-- copy/email.next-steps.3 -->
          <tr>
            <td width="28" align="left" valign="top" style="padding:0;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#896447;font-weight:700;">3.</td>
            <td valign="top" style="padding:0;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#3f4437;">From there, we can plan a time for your children and me to meet, so everyone can see how it feels before anything is decided.</td>
          </tr>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Submission summary (receipt) -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#fffdf9" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#fffdf9;background-color:#fffdf9;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#fffdf9;background-color:#fffdf9;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:22px 32px 0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:536px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="border-collapse:separate;"
      >
        <tbody>
          <tr>
            <td  style="background-color:#faf5ef;border:1px solid #e0c3a4;border-radius:12px;vertical-align:top;border-collapse:separate;padding:18px 22px 20px;">
              
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="" width="100%"
      >
        <tbody>
          <!-- copy/email.summary.h -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 0 2px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Fraunces, Georgia, 'Times New Roman', serif;font-size:16px;font-weight:600;line-height:22px;text-align:left;color:#6f5038;"
      >What you shared with me</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <table
         cellpadding="0" cellspacing="0" width="100%" border="0" style="color:#000000;font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;border:none;"
      >
        {{SUMMARY_ROWS}}
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
            </td>
          </tr>
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Button -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#fffdf9" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#fffdf9;background-color:#fffdf9;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#fffdf9;background-color:#fffdf9;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:26px 0 4px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- copy/email.cta -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 32px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="#896447" role="presentation" style="border:none;border-radius:999px;cursor:auto;mso-padding-alt:13px 30px;background:#896447;" valign="middle"
            >
              <a
                 href="https://nannymckenzie.github.io/" style="display:inline-block;background:#896447;color:#fffdf9;font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:15px;font-weight:700;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:13px 30px;mso-padding-alt:0px;border-radius:999px;" target="_blank"
              >
                Visit my site
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Signature -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#fffdf9" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#fffdf9;background-color:#fffdf9;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#fffdf9;background-color:#fffdf9;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:24px 0 30px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- copy/email.signoff -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px 2px;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:15px;line-height:24px;text-align:left;color:#3f4437;"
      >Warmly,</div>
    
                </td>
              </tr>
            <!-- copy/email.signature -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px 6px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Fraunces, Georgia, 'Times New Roman', serif;font-size:19px;line-height:26px;text-align:left;color:#6f5038;"
      >McKenzie Ochoa Conner</div>
    
                </td>
              </tr>
            <!-- copy/email.credentials -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0 32px;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:13px;line-height:20px;text-align:left;color:#896447;"
      >WA State Teacher Certified &middot; CPR and First Aid Certified</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Footer -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#e0e2cb" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#e0e2cb;background-color:#e0e2cb;margin:0px auto;max-width:600px;border-radius:0 0 14px 14px;overflow:hidden;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#e0e2cb;background-color:#e0e2cb;width:100%;border-collapse:separate;"
        >
          <tbody>
            <tr>
              <td
                 style="border-radius:0 0 14px 14px;direction:ltr;font-size:0px;padding:20px 0 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- copy/email.footer.area -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 32px 6px;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:13px;line-height:20px;text-align:center;color:#3f4437;"
      >Bellingham, WA (York Neighborhood)</div>
    
                </td>
              </tr>
            <!-- copy/email.footer.reason -->
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0 32px;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:12px;line-height:18px;text-align:center;color:#5c6050;"
      >You're receiving this note because you contacted me through <a href="https://nannymckenzie.github.io/" style="color:#5c6050;">nannymckenzie.github.io</a>.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#f4ece4" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#f4ece4;background-color:#f4ece4;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#f4ece4;background-color:#f4ece4;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:0 0 24px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:'Nunito Sans', Arial, Helvetica, sans-serif;font-size:1px;line-height:1px;text-align:left;color:#3f4437;"
      >&nbsp;</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
      </body>
    
</html>
  `
