// Compiles emails/lead-confirmation.mjml into:
//   - emails/lead-confirmation.html (browser preview with sample data)
//   - supabase/functions/submit-lead/lead-confirmation-html.ts (generated template,
//     tokens left in place for renderLeadConfirmation() to fill at send time)
// Run with: npm run email
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import mjml2html from 'mjml'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = readFileSync(join(root, 'emails/lead-confirmation.mjml'), 'utf8')

const { html, errors } = await mjml2html(source, { validationLevel: 'strict' })
if (errors?.length) {
  console.error(errors)
  process.exit(1)
}

const TOKENS = ['{{PARENT_FIRST_NAME}}', '{{SUMMARY_ROWS}}']
for (const token of TOKENS) {
  if (!html.includes(token)) {
    console.error(`compiled HTML lost token ${token}; check the MJML source`)
    process.exit(1)
  }
}

// Generated Deno module: template literal with backslashes, backticks and ${ escaped.
const literal = html.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${')
writeFileSync(
  join(root, 'supabase/functions/submit-lead/lead-confirmation-html.ts'),
  `// GENERATED by scripts/build-email.mjs from emails/lead-confirmation.mjml. Do not edit.
// Tokens ({{PARENT_FIRST_NAME}}, {{SUMMARY_ROWS}}) are filled by
// renderLeadConfirmation() in emails.ts.
export const LEAD_CONFIRMATION_HTML = \`${literal}\`
`,
)

// Browser preview with sample data mirroring what emails.ts produces.
const sampleRow = (label, value) => `<tr>
  <td align="left" valign="top" style="padding:8px 14px 0 0;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#896447;white-space:nowrap;">${label}</td>
  <td align="left" valign="top" style="padding:8px 0 0;font-family:'Nunito Sans',Arial,Helvetica,sans-serif;font-size:14px;line-height:21px;color:#3f4437;">${value}</td>
</tr>`
const preview = html
  .replaceAll('{{PARENT_FIRST_NAME}}', 'Avery')
  .replaceAll(
    '{{SUMMARY_ROWS}}',
    [
      sampleRow('Name', 'Avery Johnson'),
      sampleRow('Email', 'avery@example.com'),
      sampleRow('Phone', '(360) 555-0142'),
      sampleRow('Prefers', 'Text message'),
      sampleRow('Town', 'Bellingham'),
      sampleRow('Neighborhood', '&mdash;'),
      sampleRow('Children', 'Two, ages 2 and 4'),
      sampleRow('Start date', 'Mid September'),
      sampleRow('Schedule', 'Monday to Friday, 8 to 4'),
      sampleRow('Message', '&mdash;'),
    ].join(''),
  )
writeFileSync(join(root, 'emails/lead-confirmation.html'), preview)

console.log('wrote emails/lead-confirmation.html and supabase/functions/submit-lead/lead-confirmation-html.ts')
